Add support for HKHeartbeatSeriesSample
agencyenterprise/react-native-health pull request #130
Opened 2021-07-15 20:06 UTC by klandell

## Description

Adds support for reading the HKHeartbeatSeriesSample type.  I think HealthKit allows writing this type as well, but I don't have the bandwidth to build that our right now.

Fixes #121

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

2021-07-16 16:27 UTC, alfonsosn commented
Nit: you should probably squash your commits into a single one. It will make your PR easier to review.

2021-07-16 16:35 UTC, klandell commented
@alfonsosn Done

2021-07-19 20:54 UTC, macelai requested changes
Great job as usual

2021-07-19 20:54 UTC, macelai commented on RCTAppleHealthKit/RCTAppleHealthKit+Methods_Vitals.m
> +                // mow define the data handler for the HeartbeatSeriesQuery
Typo

2021-07-20 13:52 UTC, klandell commented on RCTAppleHealthKit/RCTAppleHealthKit+Methods_Vitals.m
> +                // mow define the data handler for the HeartbeatSeriesQuery
Oops. Typo fixed.

2021-07-23 21:48 UTC, merged