Add support for Peak Flow Expiratory Rate
agencyenterprise/react-native-health pull request #135
Opened 2021-07-21 13:24 UTC by kabaros

## Description

This PR adds support for [Peak Expiratory Flow rate](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifierpeakexpiratoryflowrate) to react-native-health library.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

2021-07-23 21:40 UTC, macelai requested changes
Amazing work! Can you also add docs to `docs/README.md` and `docs/permissions.md`?

Thanks!

2023-01-23 15:11 UTC, GGGava commented on RCTAppleHealthKit/RCTAppleHealthKit+Methods_Body.m
> +    if(startDate == nil){
I agree this is better, but currently, we don't check it on other methods, so it would be confusing to check this here.

2023-01-23 19:21 UTC, GGGava approved these changes

2023-01-23 19:22 UTC, macelai approved these changes

2023-01-23 19:23 UTC, merged