Added OxygenSaturation samples
agencyenterprise/react-native-health pull request #51
Opened 2021-03-05 20:54 UTC by buzzeh

Added the ability to get the Oxygen Saturation samples

2021-03-08 14:49 UTC, joaovpmamede commented
I was just waiting for this.
Any chance to include this in the next release @lucaspbordignon ?

2021-03-12 17:03 UTC, lucaspbordignon submitted a review, later dismissed

2021-03-12 17:03 UTC, Macelai requested changes

2021-03-12 17:05 UTC, lucaspbordignon commented
Thanks, @buzzeh

That one is a valuable addition to the project, considering the recent addition of the OxygenSaturation in Apple HealthKit

Will definitively include on the next release of the library (@joaovpmamede FYI)

2021-03-12 17:10 UTC, Macelai requested changes

2021-03-12 17:10 UTC, Macelai commented on RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
> +    else if ([@"OxygenSaturation" isEqualToString: key]) {
Just review this one, please

2021-03-12 17:29 UTC, buzzeh commented on RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m
> +    else if ([@"OxygenSaturation" isEqualToString: key]) {
Let me know if that is all, this is my first pull request, so I apologize if Im not doing it right

2021-03-12 17:33 UTC, lucaspbordignon approved these changes

2021-03-12 17:45 UTC, Macelai commented
That’s perfect! Thanks for the quick reply on that one 😄

2021-03-12 17:45 UTC, Macelai approved these changes

2021-03-12 17:46 UTC, merged

2021-03-12 19:52 UTC, lucaspbordignon commented
Released at version 1.5.0

@joaovpmamede FYI