Fix health value types for blood pressure
agencyenterprise/react-native-health pull request #91
Opened 2021-04-21 10:46 UTC by joleb

## Description

Just changed to type of `getBloodPressureSamples` to the corresponding one in the documentation (https://github.com/agencyenterprise/react-native-health/blob/master/docs/getBloodPressureSamples.md).
Here the value for `bloodPressureDiastolicValue` and `bloodPressureSystolicValue` is mentioned, but not listed as type, thus Typescript assumes it's wrong - yet it is working.
I chose to create a new interface for BloodPressureSamples, since the blood pressure values are only used there and nowhere else.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

2021-04-21 12:28 UTC, Macelai requested changes
Hey @joleb

Thanks for your contribution. As we are changing the interface to the right value, shouldn't not extending the `HealthValue`, because it doesn't have a `value` property? I think it should only have the dates, what do you think?

2021-04-21 13:11 UTC, joleb commented
> Hey @joleb
> 
> Thanks for your contribution. As we are changing the interface to the right value, shouldn't not extending the `HealthValue`, because it doesn't have a `value` property? I think it should only have the dates, what do you think?

Yes, that's true :) 
I just didn't want to change that much tbh, but it's surely the way to go. I'm going to change this.
My approach would be to create a "base" interface with both dates, then extending it for `HealthValue`with `value` and for `BloodPressureSampleValue` with `bloodPressureSystolicValue` and `bloodPressureDiastolicValue`.
Thus they always have start/endDate in common and they are much easier changeable. What is your opinion on that @Macelai ?

2021-04-21 13:35 UTC, Macelai commented
I think that would be a good idea!

2021-04-21 13:56 UTC, Macelai approved these changes
Great job!

2021-04-28 11:34 UTC, lucaspbordignon commented
Hey @joleb!

Welcome to the project and thank you for the submission. Feel free to contribute and submit any suggestion in the project 🙂

2021-04-28 11:34 UTC, merged